version: "3.9"

services: 

    jenkins:
        container_name: jenkins
        build: 
            context: .
        ports: 
            - "8080:8080"
        volumes: 
            - ./jenkins:/var/jenkins_home
        depends_on: 
            - db

    db:
        image: postgres
        restart: unless-stopped
        volumes: 
            - ./data/db:/var/lib/postgres/data
        environment:
            - POSTGRES_DB=myproject
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432
    
    api:
        build: ./api
        ports: 
            - "8000:8000"
        depends_on: 
            - db
    
    client:
        build: ./client
        ports: 
            - 8081:8081
        depends_on: 
            - db
